"""Added time collection to  Late-Log database

Revision ID: 0691d2f3ab58
Revises: 256a1cdf5e3d
Create Date: 2025-01-30 12:08:25.621443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0691d2f3ab58'
down_revision = '256a1cdf5e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('late_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_time', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('late_log', schema=None) as batch_op:
        batch_op.drop_column('log_time')

    # ### end Alembic commands ###
