"""First migrate predeployment

Revision ID: 256a1cdf5e3d
Revises: a0bcda3c69b2
Create Date: 2025-01-30 09:38:22.416503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256a1cdf5e3d'
down_revision = 'a0bcda3c69b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
