"""Ensuring all schema is updated

Revision ID: d9e7f002bd63
Revises: ece83604ccac
Create Date: 2025-01-30 12:47:27.999768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e7f002bd63'
down_revision = 'ece83604ccac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
