"""Edited some schema

Revision ID: ec01c50dbeb6
Revises: bd25c72625bc
Create Date: 2025-02-26 20:47:05.745111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec01c50dbeb6'
down_revision = 'bd25c72625bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
