"""Updated LateLog db

Revision ID: ece83604ccac
Revises: 0691d2f3ab58
Create Date: 2025-01-30 12:18:19.430509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece83604ccac'
down_revision = '0691d2f3ab58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
